name: general
permissions:
  contents: read
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v5
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo fmt --check
        run: cargo fmt --check
      - name: cargo clippy --all-features --all-targets
        run: cargo clippy --all-features --all-targets
      - name: cargo doc --no-deps --all-features
        run: cargo doc --no-deps --all-features

